apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: nationalparks
  labels:
    io.imbm.service: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      env:
        # See also: https://hub.docker.com/_/mysql
        - name: MYSQL_DATABASE
          name: nationalparks_db
        - name: MYSQL_ROOT_USERNAME
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d          
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: "mysql"
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config      
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
