apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: nationalparks
spec:
  type: LoadBalancer
  selector:
    io.imbm.service: mysql
  ports:
  - port: 3306
    targetPort: 3306
